### ISSUE TITLE
knative install fails

### ISSUE THREAD

**Issue by doddatpivotal** [failk8s/tkg-dev-install#3]
I attempted to run the install against a newly provisioned cluster with TMC.

My initial command was 

```
./tkg-dev-install full-dev -f override-duskendale.yaml -c
```

After completion, when I run...

```
± |master ✓| → kapp list
Target cluster 'https://697nk04i9lpt3pxrgp3o0vkxk55x-k8s-667086920.us-east-2.elb.amazonaws.com:443' (nodes: ip-10-0-1-206.us-east-2.compute.internal, 3+)

Apps in namespace 'default'

Name              Namespaces                              Lcs    Lca  
cert-manager      (cluster),cert-manager,kube-system      true   1h  
eduk8s            (cluster),eduk8s                        true   1h  
ingress           (cluster),cert-manager,tanzu-developer  true   29m  
knative           (cluster),knative-serving               false  15m  
kpack             (cluster),kpack                         true   22m  
kubeapps          (cluster),kubeapps                      true   1h  
registry          (cluster),tanzu-developer               true   1h  
tekton-dashboard  (cluster),tekton-pipelines              true   30m  
tekton-release    (cluster),tekton-pipelines              true   22m  
tekton-triggers   (cluster),tekton-pipelines              true   22m  
wavefront         (cluster),default,kube-system,          true   1h  
                  wavefront-collector                              

Lcs: Last Change Successful
Lca: Last Change Age

11 apps

Succeeded
```

knative appears to not have installed properly.

Then when I do...

```
./tkg-dev-install knative -f override-duskendale.yaml -c
```

I get ..

```
7:51:21PM: ---- applying 5 changes [0/22 done] ----
7:51:21PM: create customresourcedefinition/routes.serving.knative.dev (apiextensions.k8s.io/v1) cluster

kapp: Error: Applying create customresourcedefinition/routes.serving.knative.dev (apiextensions.k8s.io/v1) cluster:
  Creating resource customresourcedefinition/routes.serving.knative.dev (apiextensions.k8s.io/v1) cluster:
    CustomResourceDefinition.apiextensions.k8s.io "routes.serving.knative.dev" is invalid: 

  - spec.versions[1].schema.openAPIV3Schema: Required value: schemas are required

  - spec.versions[2].schema.openAPIV3Schema: Required value: schemas are required

 (reason: Invalid)
```

I am running k8s v1.18.5

Aside from this, I notice that when I apply the lab-markdown-sample workshop and trainingportal, the URL never gets populated and I don't see it in my hub.  I'm guessing that knative is part of the reason.

**Comment by GrahamDumpleton** [comment]
``knative`` is not used by the operator or for deployment of workshops, it is only there in case a specific workshop wanted to use it. Thus it shouldn't prevent the ability to deploy a workshop.

What do you get when you run:

```
kubectl get eduk8s
```

**Comment by doddatpivotal** [comment]
I guess I have two different issues.  One is, is knative expected to work?  I recognize it is not relavent for the workshop's i'm using.  Perhaps we just have to to add some info in the readme.  I'm guessing it is the k8s version that I have, but not sure.

As for the workshop, I appreciate your help.  Here is the result of the command you requested.

```
± |master ✓| → kubectl get eduk8s
NAME                                                   IMAGE   URL
workshop.training.eduk8s.io/lab-getting-started-k14s           https://github.com/eduk8s-tests/lab-getting-started-with-k14s
workshop.training.eduk8s.io/lab-markdown-sample                https://github.com/eduk8s/lab-markdown-sample

NAME                                                      AGE
systemprofile.training.eduk8s.io/default-system-profile   169m

NAME                                                         URL   ADMINUSERNAME   ADMINPASSWORD
trainingportal.training.eduk8s.io/lab-getting-started-k14s                         
trainingportal.training.eduk8s.io/lab-markdown-sample  
```

**Comment by GrahamDumpleton** [comment]
That URL is empty in ``TrainingPortal`` indicates that the operator is not running at all, or has failed for some reason.

What do you get for:

```
kubectl get pods -o wide -n eduk8s
```

**Comment by doddatpivotal** [comment]
```
○ → kubectl get pods -o wide -n eduk8s
NAME                               READY   STATUS    RESTARTS   AGE     IP                NODE                                      NOMINATED NODE   READINESS GATES
eduk8s-operator-848f8c655f-lfftx   1/1     Running   1          3h36m   192.168.130.174   ip-10-0-1-99.us-east-2.compute.internal   <none>           <none>
hub-7ff985d8fc-8jfjl               1/1     Running   1          3h36m   192.168.130.172   ip-10-0-1-99.us-east-2.compute.internal   <none>           <none>
```

**Comment by doddatpivotal** [comment]
I just re-ran the entire workflow on a new v1.17.8 generated by TMC.  I still faced the same knative error, but my workshop deployed successfully and I got a URL, userid and password.  I'll create separate issue for knative.  However, this issue maybe specific to the k8s version.

**Comment by GrahamDumpleton** [comment]
FWIW. One of our clusters that works is I believe 1.18.3.

**Comment by doddatpivotal** [comment]
@GrahamDumpleton  If works with the k8s version, then any suggestions on next thing to look to investigate?

**Comment by doddatpivotal** [comment]
Ok.  The issue with missing trainingportal URL's was resolved by removing eduk8s and re-deploying it.

Deleted all trainingportal and workshop resources
kapp delete -a eduk8s -c
./tkg-dev-install eduk8s -f overrides-duskendale.yaml -c (edited) 
Re applied trainingportal resources.

**Comment by doddatpivotal** [comment]
Now we just have the knative issue, which I'll keep in this issue as that was the original title.  Graham provides that knative is not necessary for eduk8s to run and that it is only there if specific workshops are require it.  So I think we should either remove knative from this repo, or fixit.  No sense in keeping in its current state to confuse users.

**Comment by jorgemoralespou** [comment]
This is now fixed
